# ApexShot Hotkeys for Hyprland
# Add these lines to your hyprland.conf

bind = SHIFT SUPER, 4, exec, /usr/bin/apexshot capture area # capture_area
bind = CTRL ALT, X, exec, /usr/bin/apexshot capture crosshair # capture_crosshair
bind = CTRL ALT SUPER, S, exec, /usr/bin/apexshot capture screen # capture_screen
bind = CTRL ALT, P, exec, /usr/bin/apexshot show-last-preview # show_last_preview
bind = CTRL ALT, R, exec, /usr/bin/apexshot record ui # open_recording_ui
bind = CTRL ALT SHIFT, S, exec, /usr/bin/apexshot record stop # recording_stop_save
